title: Vórtice de Pensamentos
email: jonatasconceicaocontato@gmail.com
name: Vórtice de pensamentos
description: >- # this means to ignore newlines until "baseurl:"
  "O que, então é capaz de nos oferecer uma orientação? Somente a filosofia." - Marco Aurélio
baseurl: ""
url: "https://jonatassc.github.io/PB" 
tags_path: /tags/


# Settings for Jekyll Compose


# Build settings
theme: jekyll-theme-tao

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-timeago



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

